### ISSUE TITLE
Images not updating with latest discord.py

### ISSUE THREAD

**Issue by DennisTT** [Gorialis/discord.py-docker#5]
Hi there,

It looks like the GitHub Actions that build and upload the Docker images have been failing for the past couple months.  There are new versions of discord.py (v2.2.2) that have been released, and I'm wondering if the images can be updated.

Thanks.

**Comment by scarletcafe** [comment]
Hi there, I fixed the workflow issue that was causing the problem (Alpine finally updated their imagemagick version) and the new images are now built, with the README on docker hub updated also.

**Comment by swanny246** [comment]
Hi, I'm wondering if this same issue is happening again? I'm trying to get 2.3.2 of Discord.py with Docker, and using tags like discord.py:full is only pulling 2.3.1. Not sure if I'm using the wrong tag or if "full" isn't updated with the right version?

**Comment by scarletcafe** [comment]
Hi, turns out if you don't commit to a repository for a while GitHub stops running scheduled workflows. I've updated the Python versions and fixed a bug in a new push, so the workflow is back up and new images with up to date versions should now be available.
